#include <Windows.h>
#include <d3d9.h>
#include <MinHook.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cwchar>
#include <intrin.h>
#include <initializer_list>
#include <mutex>
#include <vector>

#include "zachfix/core/config.h"
#include "zachfix/core/version.h"
#include "zachfix/core/logging.h"
#include "zachfix/core/main_exe.h"
#include "zachfix/render/d3d9/d3d9_scope.h"
#include "zachfix/render/frame_limiter.h"
#include "zachfix/save/save_diag.h"
#include "zachfix/gameplay/difficulty.h"
#include "zachfix/gameplay/vanilla_nan_fix.h"
#include "zachfix/gameplay/precise_game_time.h"
#include "zachfix/gameplay/skip_intro.h"
#include "zachfix/world/world_streaming.h"
#include "zachfix/world/world_alternate3d_distance.h"
#include "zachfix/input/native_gamepad.h"
#include "zachfix/input/gamepad_backend.h"
#include "zachfix/input/input_mode.h"
#include "zachfix/input/input_latency.h"
#include "zachfix/input/winmm_input_fix.h"
#include "zachfix/gameplay/combat_strafe.h"
#include "zachfix/gameplay/aim_fpu_fix.h"
#include "zachfix/audio/surround_audio_fix.h"
#include "zachfix/render/runtime_resources.h"
#include "zachfix/render/screenshot_presets.h"
#include "zachfix/ui/ui_settings.h"
#include "zachfix/render/texture_override.h"
#include "zachfix/world/house_list_fix.h"
#include "zachfix/render/postfx/postfx.h"
#include "zachfix/render/postfx/postfx_tuning.h"
#include "zachfix/render/postfx/postfx_ao.h"
#include "zachfix/render/postfx/postfx_bloom.h"
#include "zachfix/render/postfx/postfx_dof.h"
#include "zachfix/render/postfx/postfx_exposure.h"

// Implementation is split by subsystem but intentionally kept in one translation unit.
#include "zachfix/core/core.inl"
#include "zachfix/render/rendering.inl"
#include "zachfix/render/dof_blur.inl"
#include "zachfix/render/texture_filtering.inl"
#include "zachfix/render/runtime_resources.inl"
#include "zachfix/render/postfx/postfx.inl"
#include "zachfix/render/postfx/postfx_tuning.inl"
#include "zachfix/render/postfx/postfx_ao.inl"
#include "zachfix/render/postfx/postfx_bloom.inl"
#include "zachfix/render/postfx/postfx_dof.inl"
#include "zachfix/render/postfx/postfx_exposure.inl"
#include "zachfix/render/d3d9/d3d9_device.inl"
#include "zachfix/render/d3d9/d3d9_entry.inl"
#include "zachfix/core/initialization.inl"

